# Reference:
# https://github.com/SeleniumHQ/docker-selenium
# https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3-swarm.yml
# To start Docker in Swarm mode, you need to run `docker swarm init`
# To deploy the Grid, `docker stack deploy -c docker-compose-v3-swarm.yml grid`
# Stop with `docker stack rm grid`
# Stop swarm mode `docker swarm leave --force`
# HOST_URI="http://localhost:4444/wd/hub" to set in remote driver is this.
# Access docker selenium grid on "http://localhost:4444"

version: '3.7'

services:
    chrome:
        image: selenium/node-chrome:4.1.1-20220121
        shm_size: 2gb
        environment:
            - SE_EVENT_BUS_HOST=selenium-hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
        deploy:
            replicas: 4
        entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'

    edge:
        image: selenium/node-edge:4.1.1-20220121
        shm_size: 2gb
        environment:
            - SE_EVENT_BUS_HOST=selenium-hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
        deploy:
            replicas: 4
        entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'

    firefox:
        image: selenium/node-firefox:4.1.1-20220121
        shm_size: 2gb
        environment:
            - SE_EVENT_BUS_HOST=selenium-hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
        deploy:
            replicas: 4
        entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'

    selenium-hub:
        image: selenium/hub:4.1.1-20220121
        ports:
            - "4442:4442"
            - "4443:4443"
            - "4444:4444"
